### ISSUE TITLE
не получается почитать код

### ISSUE THREAD

**Issue by LedinecMing** [kemazode/DiscordTimesJSPublic#2]
Исходный код обфусцировали хакеры, уважаемый @kemazode срочно исправьте эту оплошность!!

**Comment by kemazode** [comment]
Hi, we apologize for the obfuscation of the source code caused by hackers. We are taking all necessary measures to resolve the issue and will keep you updated.

**Comment by LedinecMing** [comment]
че закрыл то? чини
